#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup

from base64 import urlsafe_b64encode
from hashlib import blake2b
from indy_common.config_util import getConfig
from indy_common.config_helper import ConfigHelper, NodeConfigHelper
from indy_common.txn_util import getTxnOrderedFields
import argparse
import logging
import sys


portsStart = 9700
nodeParamsFileName = 'indy.env'


parser = argparse.ArgumentParser()
parser.add_argument('--key', default='')
args, remaining_args = parser.parse_known_args()

key = args.key.encode()
sys.argv[1:] = remaining_args


if __name__ == "__main__":
    logger = logging.getLogger()
    logger.disabled = True

    TestNetworkSetup.getSigningSeed = lambda name: urlsafe_b64encode(blake2b(name.encode(), key=key, digest_size=24).digest())\
        if key != b'' else ('0' * (32 - len(name)) + name).encode()

    TestNetworkSetup.bootstrapTestNodes(getConfig(), portsStart, nodeParamsFileName,
                                        getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
